{{- if .Values.persistence.quarantine.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "email-auth-gateway.fullname" . }}-quarantine-pvc
  labels:
    {{- include "email-auth-gateway.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.quarantine.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.quarantine.storageClass }}
  storageClassName: {{ .Values.persistence.quarantine.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.quarantine.size }}
---
{{- end }}
{{- if .Values.persistence.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "email-auth-gateway.fullname" . }}-logs-pvc
  labels:
    {{- include "email-auth-gateway.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode | default "ReadWriteOnce" }}
  {{- if .Values.persistence.logs.storageClass }}
  storageClassName: {{ .Values.persistence.logs.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }}
