{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "email-auth-gateway.fullname" . }}-secrets
  labels:
    {{- include "email-auth-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  WEBHOOK_SHARED_SECRET: {{ .Values.secrets.webhookSharedSecret | b64enc | quote }}
  ADMIN_SHARED_SECRET: {{ .Values.secrets.adminSharedSecret | b64enc | quote }}
  RAW_MAIL_ENCRYPTION_KEY: {{ .Values.secrets.rawMailEncryptionKey | default "" | b64enc | quote }}
  RELAY_USERNAME: {{ .Values.secrets.relayUsername | default "" | b64enc | quote }}
  RELAY_PASSWORD: {{ .Values.secrets.relayPassword | default "" | b64enc | quote }}
  VT_API_KEY: {{ .Values.secrets.vtApiKey | default "" | b64enc | quote }}
  GSB_API_KEY: {{ .Values.secrets.gsbApiKey | default "" | b64enc | quote }}
  QUARANTINE_NOTIFY_WEBHOOK_URL: {{ .Values.secrets.quarantineNotifyWebhookUrl | default "" | b64enc | quote }}
{{- end }}
